In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(
    "dados.xlsx",
    sheet_name=0,
    header=1,          # usa a 2ª linha como cabeçalho real
    dtype={"Class. Por idade": str},  # evita converter "1" em número se quiser
)

df.columns = (
    df.columns.astype(str)
    .str.replace("\n", " ", regex=False)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)
# Renomeado as colunas
df = df.rename(columns={
    "Nome": "nome",
    "Class. Por idade": "class_idade",
    "Data nascimento": "data_nascimento",
    "Data 1ª consulta": "data_primeira_consulta",
    "Tempo entre início dos sintomas e primeira consulta": "intervalo_sintomas_primeira_consulta",
    "Sexo": "sexo",
    "Tipo": "tipo",
    "Perda de peso": "perda_peso",
    "Idade (meses) início dos sintomas": "intervalo_nascimento_sintomas",
    "Data 1ª colono": "data_primeira_colono",
    "Unnamed: 10": "intervalo_sintomas_primeira_colo",
    "Classificação": "classificacao",
})

df = df.drop(index=0).reset_index(drop=True)

colunas_data = ["data_nascimento", "data_primeira_consulta", "data_primeira_colono"]

for col in colunas_data:
    df[col] = pd.to_datetime(df[col], errors="coerce").dt.strftime("%d/%m/%Y")

df = df.drop(columns=["nome"])

for index,tempo in enumerate(df['intervalo_sintomas_primeira_consulta'].tolist()) : 
     tempo_meses = tempo.replace("meses","")
     df.loc[index,'intervalo_sintomas_primeira_consulta'] = tempo_meses


df["intervalo_sintomas_primeira_consulta"] = pd.to_numeric(
    df["intervalo_sintomas_primeira_consulta"],
    errors="coerce"
)
df["intervalo_sintomas_primeira_consulta"] = (
    df["intervalo_sintomas_primeira_consulta"].astype("Int64")
)

In [4]:
df

,class_idade,data_nascimento,data_primeira_consulta,intervalo_sintomas_primeira_consulta,sexo,tipo,perda_peso,intervalo_nascimento_sintomas,data_primeira_colono,intervalo_sintomas_primeira_colo,classificacao
0,VEOIBD,27/09/2013,02/03/2023,54,F,Enterorragia,não,60,15/07/2019,6 meses,CU
1,VEOIBD,25/10/2024,09/06/2026,5,F,Enterorragia,Não,14,20/05/2026,4 meses,CNC
2,DI Ped,01/01/2006,04/05/2021,13,F,Dor abdominal,Não,168,13/04/2020,1 mês,DC
3,VEOIBD,19/04/2019,03/08/2023,34,F,Diarreia,Não,18,01/05/2022,19 meses,CNC
4,Início precoce,18/05/2012,19/01/2023,20,F,Febre,sim,108,26/01/2023,30 meses,DC
...,...,...,...,...,...,...,...,...,...,...,...
96,Início precoce,08/08/2012,20/10/2022,26,M,Dor abdominal,Sim,96,01/09/2022,25 meses,DC
97,Início precoce,05/03/2004,19/07/2011,4,M,Diarreia,Não,84,01/06/2011,3 meses,DC
98,DI Ped,25/04/2008,05/01/2021,3,F,Diarreia,Não,144,26/10/2020,1 mês,DC
99,VEOIBD,19/05/2017,11/03/2022,11,F,Enterorragia,Sim,47,29/09/2021,5 meses,DC
100,VEOIBD,13/10/2022,26/02/2026,35,M,Enterorragia,Não,5,27/07/2024,16 meses,CNC

In [5]:
# Criar uma nova coluna data inicio sintomas

# DATA INICICO SINTOMAS =. DATA NASCIMENTO + TEMPO EM MESES

# RECRIAR A COLUNA Tempo entre inicio dos sintomas e 1ª colono = DATA 1 COLO - DATA INICICO SINTOMAS

In [6]:
datas = pd.to_datetime(df["data_nascimento"], format="%d/%m/%Y", errors="coerce")
meses = df["intervalo_nascimento_sintomas"]

df["data_inicio_sintomas"] = [
    d + pd.DateOffset(months=int(m)) if pd.notna(d) and pd.notna(m) else pd.NaT
    for d, m in zip(datas, meses)
]
df['data_inicio_sintomas'] = pd.to_datetime(df['data_inicio_sintomas'], errors="coerce").dt.strftime("%d/%m/%Y")

In [7]:
df[['data_nascimento','intervalo_nascimento_sintomas','data_inicio_sintomas']]

    data_nascimento intervalo_nascimento_sintomas data_inicio_sintomas
0        27/09/2013                            60           27/09/2018
1        25/10/2024                            14           25/12/2025
2        01/01/2006                           168           01/01/2020
3        19/04/2019                            18           19/10/2020
4        18/05/2012                           108           18/05/2021
..              ...                           ...                  ...
96       08/08/2012                            96           08/08/2020
97       05/03/2004                            84           05/03/2011
98       25/04/2008                           144           25/04/2020
99       19/05/2017                            47           19/04/2021
100      13/10/2022                             5           13/03/2023

[101 rows x 3 columns]